Update cromup

diff --git a/cromup b/cromup
--- a/cromup
+++ b/cromup
@@ -41,13 +41,6 @@ fi
 
 if [ "$remote_epoch" -le "$local_epoch" ]; then
     echo -e "\e[1;32mCromite è già aggiornato. Proseguo con altre verifiche...\e[0m"
-# == Installazione di upcromup in caso di Cromite già aggiornato ==
-    echo -e "\e[1;32mVerifica di aggiornamenti di upcromup online...\e[0m"
-sleep 3
-    # wget -O "$UPCROMUP_DIR" "$UPCROMUP_URL"
-    curl -fL --progress-bar -o "$UPCROMUP_DIR" "$UPCROMUP_URL" || { echo -e "\e[1;32mErrore nel download dell'aggiornamento di upcromup!\e[0m"; exit 1; }
-    sudo chmod a+x "$UPCROMUP_DIR"
-    ~/Cromite/upcromup
 # == Installazione di uncromup in caso di Cromite già aggiornato ==
     echo -e "\e[1;32mVerifica di aggiornamenti di uncromup online...\e[0m"
     sleep 3
@@ -55,6 +48,13 @@ sleep 3
     curl -fL --progress-bar -o "$UNCROMUP_DIR" "$UNCROMUP_URL" || { echo -e "\e[1;32mErrore nel download dell'aggiornamento di uncromup!\e[0m"; exit 1; }
     sudo cp "$UNCROMUP_DIR" "$UNCROMUP_PATH"
     sudo chmod a+x "$UNCROMUP_PATH"
+# == Installazione di upcromup in caso di Cromite già aggiornato ==
+    echo -e "\e[1;32mVerifica di aggiornamenti di upcromup online...\e[0m"
+sleep 3
+    # wget -O "$UPCROMUP_DIR" "$UPCROMUP_URL"
+    curl -fL --progress-bar -o "$UPCROMUP_DIR" "$UPCROMUP_URL" || { echo -e "\e[1;32mErrore nel download dell'aggiornamento di upcromup!\e[0m"; exit 1; }
+    sudo chmod a+x "$UPCROMUP_DIR"
+    ~/Cromite/upcromup
     exit 0
 fi
 sleep 2
